### ISSUE TITLE
Gstreamer error on some IPTV channels.

### ISSUE THREAD

**Issue by 68foxboris** [fairbird/openpli-dreambox-oe-core#17]
Good afternoon. When using a new streamer a crash occurs on some iptv channels.There are no problems on sat channels.
You can watch iptv channels for a long time and when you switch to the next channel a crash occurs.

`
<115125.7874> [eServiceMP3] state transition NULL -> READY
<115127.2687> [eServiceMP3] Gstreamer error: Couldn't retrieve key for decryption (13) from hlsdemux58
<115127.8120> PC: b6999b48
<115127.8121> Fault Address: 00000008
<115127.8121> Error Code: 519
<115127.8123> Backtrace:
<115127.8124> /usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x78A10]
<115127.8127> /lib/libc.so.6(__default_rt_sa_restorer) [0xB618A0F0]
<115127.8127> -------FATAL SIGNAL 11

`

**Comment by fairbird** [comment]
Good afternoon.
Please I need full log not just some lines from crash ...
Because on my DM920 no problem ... Is your device is Dreambox ?!! What model ?!

**Comment by 68foxboris** [comment]
This crash does not depend on the receiver and as I understand it,appears if something is wrong with the channel.
It is in the list, but in fact it does not work and when you switch to it it immediately crashes.There was no crash on the previous gstreamer.
There, when switching to a problematic channel, it's just a blank screen.
`
<291872.2576> [eServiceMP3] stop state:READY pending:PLAYING ret:FAILURE
<291768.1897> [eServiceMP3] Gstreamer error: Internal data stream error. (1) from source
<291768.1897> [eServiceMP3] Gstreamer error: Stream doesn't contain enough data. (4) from typefindelement7

`

**Comment by fairbird** [comment]
You did not answered me ... What kind of device is it dreambox Because I can not support any device if not dreambox?!!
My source just for dreambox support !!!
Every things depend on device what you are using (features build from meta)
Also you can try to change the player from ServiceApp plugin ans test Iptv with internal eplayer or test gstplayer !!
...................
or you can try to build image with old gstreamer before this commit
https://github.com/fairbird/openpli-dreambox-oe-core/commit/303b37f5e977f53906acde6b384ca7ac798894f0
