### ISSUE TITLE
help errore

### ISSUE THREAD

**Issue by ghost** [fairbird/openpli-dreambox-oe-core#7]
hi friend i'm trying to compile for a DM800se with your openpli-dreambox-oe-core and when it reaches 40% it gives me this error can you tell me what I can do thanks:

ERROR: transmission-3.00-r0 do_fetch: Fetcher failure: Unable to find revision bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd in branch master even from upstream
ERROR: transmission-3.00-r0 do_fetch: Fetcher failure for URL: 'gitsm: //github.com/transmission/transmission'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/elcobra/Musica/openpli-dreambox-oe-core/build/tmp/work/mips32el-oe-linux/transmission/3.00-r0/temp/log.do_fetch.3239951
ERROR: Task (/home/elcobra/Musica/openpli-dreambox-oe-core/meta-openembedded/meta-oe/recipes-connectivity/transmission/transmission_git.bb:do_fetch) failed with exit code '1'

**Comment by fairbird** [comment]
Update your build directory and try again after this commit ....
https://github.com/fairbird/openpli-dreambox-oe-core/commit/d7b0e802726b4ed7b5267a166339a0c005fa5a34

**Comment by ghost** [comment]
Good morning friend thank you for having replied that I did or even canceled the build starts then reaches 40% and gives me the same error

**Comment by fairbird** [comment]
The version of transmission is coming with build directly from enigma2-plugins
https://github.com/OpenPLi/enigma2-plugins/tree/master/transmission

But in your error log I have seen the build tried to connect with (github.com/transmission/transmission)
So I believe you are using  extra recipe file. maybe from (oe-alliance) ..
In this case I can not  supported Because not from my source... you need to remove it or try to help yourself.

**Comment by ghost** [comment]
Thanks friend for information but I have not changed anything I download the core and give the commands to compile

**Comment by fairbird** [comment]
Ok .. The file is from meta-openembedded .. 
I will check it again as soon as possible ...
Because the srv of (bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd) already in source
https://github.com/transmission/transmission/commit/bb6b5a062ee594dfd4b7a12a6b6e860c43849bfd
Why you can not connect with that commit (Stranger) !!

**Comment by ghost** [comment]
Thanks friend for information I check to see when the modified and then I try thanks a lot

**Comment by fairbird** [comment]
@Torros-Team
Solved with this commit 
https://github.com/fairbird/openpli-dreambox-oe-core/commit/35a19de9d01a137dc3020c01f809bd0f5c9805d9

So you need first to delete all sources regarding transmission in /sources  directory (5 peaces or so).
Then update your build tree and start again to  build image and then give me feedback later.

**Comment by ghost** [comment]
Good morning friend thank you very much for the work you did at the moment I am filling out is 
Currently  1 running tasks (6322 of 6355)  99%

**Comment by ghost** [comment]
Hi friend, as I wrote above, he got there but then he gave me this error maybe there is something wrong yet.
ERROR: Task (/home/elcobra/Documenti/openpli-dreambox-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_compile) failed with exit code '1'

**Comment by fairbird** [comment]
Let him eo delete build folder and start clone new one .... He have some wrong files ..
With me now everythings works just fine .

**Comment by enry74** [comment]
Hello friend good evening thanks for the work we did finally I was able to compile
