### ISSUE TITLE
information

### ISSUE THREAD

**Issue by open-cobralibero** [fairbird/openpli-dreambox-oe-core#79]
evening friend this is a problem when I modify the enigma2 the linch to put my skins instead of the openpli gives me an error and doesn't install me even if I implement my own plugins like . before you switched to python3 I could do it now I don't have to change anything thanks

**Comment by fairbird** [comment]
Hello friend.

If you change anything in a personal way. Then no issue here. You should be to support your change. Not in here in source core .
So please close this issue. And mentioned my name to your git source. Then maybe I can help you.

Here We can not change original recipes. Because no problem at all .
